### ISSUE TITLE
run .xml file

### ISSUE THREAD

**Issue by rwildermuth** [rwildermuth/atlantisom#1]
Hi @gavinfay and @sgaichas,

The current atlantisom function run_truth() [https://github.com/rwildermuth/atlantisom/blob/master/R/run_truth.R](url) uses a biology .xml file "based on input from the "[...]_run.prm" file" to do some of the catch corrections (lines 216 to 262). Does the old code base use this .xml output format? I can't find it in the example output Gavin provided. 

Sarah: would using just the _run.prm file work for these calculations?

Thank you,
Robert

**Comment by sgaichas** [comment]
The function loading the run parameters [load_runprm()](https://github.com/rwildermuth/atlantisom/blob/master/R/load_runprm.R) is expecting xml as an input, probably because it is easier to search for the correct attributes and associated values. I *think* the prm file has the same information, so you can get it from there but it may be harder to code. 

On the other hand, it is only pulling out a few things from that file, so you could just create it by hand. output looks like this (from NOBA model):
$toutstart
[1] 0

$toutinc
[1] 73

$toutfinc
[1] 73

$tstop
[1] 52560

$nyears
[1] 144

$timestep
[1] 12

$timestepunit
[1] "Hours"

$outputstep
[1] 73

$outputstepunit
[1] "days"

$hemisphere
[1] "northern"

$nspp
[1] 53

$nfleet
[1] 27

**Comment by gavinfay** [comment]
agreed - probably easiest to create own list object. @gavinfay to do this for the fixed effort scenario.

**Comment by gavinfay** [comment]
commit [d0b8785](#d0b8785) adds function `load_neus_v1_runprm()` to build this object.
