### ISSUE TITLE
Time periods from CATCH.nc vs Catch.txt

### ISSUE THREAD

**Issue by rwildermuth** [rwildermuth/atlantisom#2]
Hi @sgaichas, I'm trying to compare the output in [run_truth()](https://github.com/rwildermuth/atlantisom/blob/master/R/run_truth.R) for the 'bio_catch' and 'catch_all' as done in lines 304-306, but even with the time conversion from rumprm, there are different values. This is true for the SETas example also. In NEUS v1 'bio_catch' has 204 time steps from 0 to 203. These are composed in load_nc() using the length of the time dimention from the CATCH.nc file. The Catch.txt file only has 52 time steps, which are roughly one year apart.

For the SETas example, there are 62 time steps in CATCH.nc (and the resulting 'catch' table), but only 7 time steps in the Catch.txt file. Are these time steps the same, or is there another aggregating step needed before we can compare to the Catch.txt data? If they should be the same, why are they different lengths?

Thank you,
Robert

**Comment by sgaichas** [comment]
I think the .txt outputs used to default to annual, while the outputs from .nc are at the subannual level. Sounds like the output frequency toutinc and toutfinc was 90 for NEUS v1 so that would be about 4 per year for the .nc files (~200) but it is a 50 year run so you get 52 (a 0 timestep and something extra?) for annual output in the .txt file. 

@gavinfay is this correct? 

So summing every ~4 outputs from .nc should roughly follow the annual .txt? the only way to get exact matches is with toutfinc set to 73, 5 output timesteps per year.

**Comment by rwildermuth** [comment]
Right, so the way to get proportions for the Georges Bank bounds would be to look at every ~4th output in the 'bio_catch'? Or do the values need to added in groups of four? Maybe that proportion is the same all the time, though.

**Comment by sgaichas** [comment]
Sum them over each group of four ("year") in case fishery effort was not spread evenly throughout the year; one quarter may not be representative of the annual total.

**Comment by rwildermuth** [comment]
Thank you. I guess I'll handle this outside of run_truth() for now.
